# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-15 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_user_yaer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='yaer',
        ),
    ]
