# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-15 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0003_remove_user_yaer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
