# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-16 03:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0004_user_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='ima_name',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
