# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-21 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0006_auto_20191121_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_url',
            field=models.ImageField(storage=system.storage.ImageStorage(), upload_to='static/userimages'),
        ),
    ]
