# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-23 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0007_auto_20191121_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='time',
            field=models.DateField(null=True),
        ),
    ]
