# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-23 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0008_userdetails_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='province',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
