# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-19 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
