# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-19 02:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0003_community_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_status', models.CharField(max_length=20, null=True, verbose_name='0是没有点赞,1是点赞')),
                ('community', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Community')),
                ('user', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_userlike',
            },
        ),
    ]
